datawarehouse:
  target: dev
  outputs:
    dev:
      dataset: Revenue
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west9
      method: service-account-json
      priority: interactive
      project: rocadata

      threads: 4
      type: bigquery

      keyfile_json:
        type: service-account
        project_id: rocadata
        private_key_id: "{{ env_var('GCP_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('GCP_PRIVATE_KEY') }}"
        client_email: dbt-bigquery-datawarehouse@rocadata.iam.gserviceaccount.com
        client_id: "109160353603982489186"
        auth_uri: https://accounts.google.com/o/oauth2/auth
        token_uri: https://oauth2.googleapis.com/token
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/dbt-bigquery-datawarehouse%40rocadata.iam.gserviceaccount.com
