datawarehouse:
  target: dev
  outputs:
    dev:
      dataset: "{{ env_var('BIGQUERY_DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west9
      method: service-account
      priority: interactive
      project: "{{ env_var('BIGQUERY_PROJECT') }}"
      
      threads: 4
      type: bigquery

      keyfile_json:
        type: "service_account"
        project_id: "rocadata"
        private_key_id: "7351439b3b8aca0ce539af7f110d4541228b748a"
        private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC4cw+Q3OveLjJq\ny77BczPi7THKiwdzD8Cids/TBH/Wh5MF1ALOruxigO8Q3l1dGrBSjcF0PKrtFxZ2\n9gaTxlzUyp6ReGfPBy09Shz9Yc4GIyrcaFaP4w7TncmS/6PaHerC7+lyJyBD04+E\nqtb0Rm8plcPAHLklSahRqnDu7lz5pn1+ci+9f/XIpTQqpOcqGNiNaWd3lGmDsxwG\nI0pRGfSm1rSbXaVESwX9GFYaz/LuZfSLxS9tHz0i17H1FffSs/dmZHRLD07nJLTV\nW0vX/GchFLNANzjqKVo/X9J7pLiGvM7nALCqSHUPGNf9e2HCwS0VEj5WA9/NrxIb\n094x08CHAgMBAAECggEACG4AbvNHIliD0bFYbqM9t/11fOy9XUBXN6BCH5eWjMRA\nb2VA8EI6p8Z9u+HLFuINNJCpn+QqlFBYT1KE0BnM4fq/+XpXwDSd7YL8GoZu8dqH\nRHB4+ErSbCXLccOWMPXqEJkCAcdmUu3nIr3jZLbtW1NZZr0epw9xOQjsRWHbxPBc\n10vs2fQDA/9LI5xGO3AUou0XkeEuM/jsDiV11ledLILjKv8jdgeRvNGQUItnoyLs\nYJ/XqWcrZPhL18jP9hyJJVaN84oQvf+X9flhcjYoOppLFvL6+HFg8Bmj1hRiMFNk\nEYOodeS1Bj0nnVhQ+mbez5CW2RsEm3GM4kJEfk4MlQKBgQDwzwAbiqB8FsDVGjgr\nCapdWxf7rH7DG9eRgtGCtKdRK2dmv8daATMIiPicSwtu60C3YWXAxe+eZtsGAxOv\n96PKYeTd7wpuxi2XDVrv63A8aHS784U9ZcQyctTgtt1Qa8/7PDLeo1MoTQ2qeiCh\n1t1gjNwf9I6HCY+96FIiLLrA5QKBgQDEFd/IVt4yK0qgM4hBeMvPK9hv6Z57ajnQ\nMcsB7vlpKn0MtdNPR3M8bUZVRi7pXPhofsj+NY1tdmz/IVi6ViCisYgYcDefCYDX\nluluYLyQFPXOI4jy8rj/nXv6aTTX+AgoehDufBFTviOxJxvQvZd7z2rVUJbcmB6s\nlI95Rmwg+wKBgAe2aYd4SimPRP/ORixCs/0ndL4vySOQmbfkW7d298DmxfoJfGYK\nkcrdMDE5ShV0XW9CJFMnQ8RsAOnRYWkKYmmR9xWQmWHw4Pbsi5QRk1er9MksRIEx\n6DXBbcYAtVflDBU82Vg+HOS2ixCBttfYHOEBwe8YExSKHttzPGYxzo1tAoGAa4E+\npt0Rh1n62ShHrPWocBYu3PStwiY0OjQChDXcIk98LerGRrH6uQeERx5qe+FQBCJ2\n2gDMYFZMXfiPZ+HulKRW5Gcp55TTQd/obW62Exyaw4DyBZkT2nkiTuE9aqb++goq\nnEYDTfFyKh8x/djkY6oNfZRokdsI/j+ZBbmZcN8CgYBxKm8eGkgMPp19Ahcl2I3V\nw1rSRd1BlBg/k0OFXMW41og91yds5vTm9tRYgJOVB5HZ0z58KGr060W1H1nMdN2w\nnO99DrqTyXwpnu1M2oIibxNqbP2q2YKrG52f1uV0zMf4LQPEFAfVxwutMEOBZOFf\nJwi3kJQVg/w7IEiJlrm4PA==\n-----END PRIVATE KEY-----\n"
        client_email: "dbt-bigquery-datawarehouse@rocadata.iam.gserviceaccount.com"
        client_id: "109160353603982489186"
        auth_uri: "https://accounts.google.com/o/oauth2/auth"
        token_uri: "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
        client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/dbt-bigquery-datawarehouse%40rocadata.iam.gserviceaccount.com"


