datawarehouse:
  target: "{{ env_var('DBT_TARGET', 'prod') }}"
  outputs:
    prod:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('BIGQUERY_PROJECT') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET') }}"
      location: "{{ env_var('BIGQUERY_LOCATION', 'US') }}"
      threads: 4
      timeout_seconds: 300
      priority: interactive
      keyfile_json: "{{ env_var('BIGQUERY_SERVICE_ACCOUNT_JSON') }}"

