datawarehouse:
  target: dev
  outputs:
    dev:
      dataset: "{{ env_var('BIGQUERY_DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ fromjson(env_var('BIGQUERY_SERVICE_ACCOUNT_JSON')) }}"
      location: europe-west9
      method: service-account
      priority: interactive
      project: "{{ env_var('BIGQUERY_PROJECT') }}"
      threads: 4
      type: bigquery

