name: Daily dbt Build

on:
  schedule:
    - cron: "0 4 * * *" # 4am UTC which is 6am in Paris
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: dbt-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    env: # 👈 Define environment variables here
      BQ_TABLE: my_dataset.my_table
      GCP_PRIVATE_KEY_ID: ${{ secrets.GCP_PRIVATE_KEY_ID }}
      META_TOKEN: "sdkjqkldjqlkdjqljdqlkjdlqksjdqlksjkl"
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello, world!"

  build:
    needs: [setup]
    runs-on: ubuntu-latest
    env:
      GCP_PRIVATE_KEY_ID: ${{ secrets.GCP_PRIVATE_KEY_ID }}
      GCP_PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt (BigQuery adapter)
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-bigquery>=1.6,<2.0"

      - name: Show dbt version
        run: dbt --version

      - name: Run dbt build
        run: dbt build --profiles-dir ./profiles

      - name: Upload dbt logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dbt-logs
          path: |
            datawarehouse/logs/**
            datawarehouse/target/run_results.json
          if-no-files-found: ignore

    timeout-minutes: 60
